<?php

namespace Fwk\Form;

/**
 * Test class for Form.
 * Generated by PHPUnit on 2012-10-11 at 10:56:34.
 */
class BasicFormTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Form
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $form = new Form;
        $check  = new Elements\Checkbox('test_check');
        $text   = new Elements\TextArea('test_textarea');

        $check->filter(new Validation\NotEmptyFilter(), 'check must be checked');
        $text->filter(new Validation\NotEmptyFilter(), 'text must not be blank');

        $form->addAll(array($check, $text));
    }

    public function testValidationBeforeSubmitException()
    {
        $this->setExpectedException('\Fwk\Form\Exceptions\NotSubmittedException');
        $this->object->validate();
    }

    public function testValidationFail()
    {
        $this->object->submit(array(
            'test_check' => null,
            'test_textarea' => null
        ));

        $this->assertFalse($this->object->validate());
        $this->assertEquals(2, count($this->object->getErrors()));
    }

    public function testValidationPass()
    {
        $this->object->submit(array(
            'test_check' => true,
            'test_textarea' => "some test text"
        ));

        $this->assertTrue($this->object->validate());
    }

    public function testDoubleSubmitException()
    {
        $this->setExpectedException('\Fwk\Form\Exceptions\AlreadySubmittedException');
        $this->object->submit(array(
            'test_check' => true,
            'test_textarea' => "some test text"
        ));
        $this->object->submit(array());
    }
}
