<?php

namespace Fwk\Form;

/**
 * Test class for Form.
 * Generated by PHPUnit on 2012-10-11 at 10:56:34.
 */
class FiltersTest extends \PHPUnit_Framework_TestCase {
    /**
     */
    public function testEmailFilter()
    {
        $filter = new Validation\EmailFilter();
        $this->assertTrue($filter->validate("joe@bar.com"));
        $this->assertTrue($filter->validate("joe.name@bar.com"));
        $this->assertFalse($filter->validate("@bar.com"));
        $this->assertFalse($filter->validate("bar.com"));
        $this->assertFalse($filter->validate("bar"));
    }

    /**
     */
    public function testEqualsFilter()
    {
        $filter = new Validation\EqualsFilter("test");
        $this->assertTrue($filter->validate("test"));
        $this->assertFalse($filter->validate("notTest"));
    }

    /**
     */
    public function testInArrayFilter()
    {
        $filter = new Validation\IsInArrayFilter(array("one", "two", "three"));
        $this->assertTrue($filter->validate("one"));
        $this->assertTrue($filter->validate("two"));
        $this->assertFalse($filter->validate("four"));
        $this->assertFalse($filter->validate(3));
    }

    /**
     */
    public function testLengthFilter()
    {
        $filter = new Validation\LengthFilter(2, 5);
        $this->assertTrue($filter->validate("one"));
        $this->assertTrue($filter->validate("two"));
        $this->assertFalse($filter->validate("thisIsTooLong"));
        $this->assertFalse($filter->validate("o"));
        $this->assertTrue($filter->validate(array(1,2)));
        $this->assertFalse($filter->validate(array(1,2,3,4,5,6)));
    }

    /**
     */
    public function testNotEmptyFilter()
    {
        $filter = new Validation\NotEmptyFilter();
        $this->assertTrue($filter->validate("test"));
        $this->assertFalse($filter->validate(""));

        $this->assertTrue($filter->validate(array("one")));
        $this->assertFalse($filter->validate(array()));
    }

    /**
     */
    public function testRegexFilter()
    {
        $filter = new Validation\RegexFilter("/[joe|test]@bar\.com/");
        $this->assertTrue($filter->validate("joe@bar.com"));
        $this->assertFalse($filter->validate("coucou"));
    }

    /**
     */
    public function testUrlFilter()
    {
        $filter = new Validation\UrlFilter();
        $this->assertTrue($filter->validate("http://www.google.com"));
        $this->assertFalse($filter->validate("/www.google.com"));
        $this->assertFalse($filter->validate("www.google.com"));
    }

    /**
     */
    public function testDateFilter()
    {
        $filter = new Validation\DateFilter();
        $this->assertTrue($filter->validate("12/12/2012"));
        $this->assertTrue($filter->validate("12-12-2012"));
        $this->assertFalse($filter->validate("12345"));
        $this->assertFalse($filter->validate("abcdef"));
    }
}