<?php use Fwk\Form\Element; ?>
<?php if($element->hasLabel() &&
        $element->attribute(Element::ATTR_LABEL_POSITION, Element::LABEL_POSITION_LEFT) == Element::LABEL_POSITION_LEFT): ?>
        <label for="<?php echo $element->getFirstId(); ?>"><?php echo htmlspecialchars($element->getLabel()); ?></label>
<?php endif; ?>
<?php foreach($element->elements() as $element): ?><?php include $this->getElementResource($element); ?><?php endforeach; ?>
<?php if($element->hasHint()): ?>
        <span class="hint"><?php echo htmlspecialchars($element->getHint()); ?></span>
<?php endif; ?>
<?php if($element->hasLabel() &&
        $element->attribute(Element::ATTR_LABEL_POSITION) == Element::LABEL_POSITION_RIGHT): ?>
        <label for="<?php echo $element->getFirstId(); ?>"><?php echo htmlspecialchars($element->getLabel()); ?></label>
<?php endif; ?>