<?php use Fwk\Form\Element, Fwk\Form\Elements\Checkbox; ?>
<?php if($element->hasLabel() &&
        $element->attribute(Element::ATTR_LABEL_POSITION, Element::LABEL_POSITION_LEFT) == Element::LABEL_POSITION_LEFT): ?>
        <label for="<?php echo $element->attribute(Element::ATTR_ID, $element->getName()); ?>"><?php echo htmlspecialchars($element->getLabel()); ?></label>
<?php endif; ?>
        <input type="<?php echo (isset($type) ? $type : 'text'); ?>"<?php
foreach($element->attributes() as $attr => $value):
if(strpos($attr, '_', 0) !== false || $attr == Element::ATTR_VALUE) { continue; }
if(empty($value)) { continue; }
?> <?php echo $attr; ?>="<?php echo htmlspecialchars($value); ?>"<?php endforeach; ?>
<?php
    $value = $element->valueOrDefault();
    if(!empty($value) && !$element instanceof Checkbox):
?> value="<?php echo htmlspecialchars($element->valueOrDefault()); ?>"<?php endif; ?> />
<?php if($element->hasHint()): ?>
        <span class="hint"><?php echo htmlspecialchars($element->getHint()); ?></span>
<?php endif; ?>
<?php if($element->hasLabel() &&
        $element->attribute(Element::ATTR_LABEL_POSITION) == Element::LABEL_POSITION_RIGHT): ?>
        <label for="<?php echo $element->attribute(Element::ATTR_ID, $element->getName()); ?>"><?php echo htmlspecialchars($element->getLabel()); ?></label>
<?php endif; ?>