<?php use Fwk\Form\Element; ?>
<?php if($element->hasLabel() &&
        $element->attribute(Element::ATTR_LABEL_POSITION, Element::LABEL_POSITION_LEFT) == Element::LABEL_POSITION_LEFT): ?>
        <label for="<?php echo $element->attribute(Element::ATTR_ID, $element->getName()); ?>"><?php echo htmlspecialchars($element->getLabel()); ?></label>
<?php endif; ?>
        <select<?php
foreach($element->attributes() as $attr => $value):
if(strpos($attr, '_', 0) !== false || $attr == Element::ATTR_VALUE) { continue; }
elseif($attr == Element::ATTR_NAME && $element->isMultiple()) { $value .="[]"; }
?> <?php echo $attr; ?>="<?php echo htmlspecialchars($value); ?>"<?php $value = $element->valueOrDefault(); endforeach; ?>>
<?php foreach ($element->getOptions() as $key => $opt): ?>
            <option value="<?php echo htmlentities($key) ?>"<?php if($element->isOptionSelected($key)): ?> selected="selected"<?php endif; ?>><?php echo htmlentities($opt) ?></option>
<?php endforeach; ?>
        </select>
<?php if($element->hasHint()): ?>
        <span class="hint"><?php echo htmlspecialchars($element->getHint()); ?></span>
<?php endif; ?>
<?php if($element->hasLabel() &&
        $element->attribute(Element::ATTR_LABEL_POSITION) == Element::LABEL_POSITION_RIGHT): ?>
        <label for="<?php echo $element->attribute(Element::ATTR_ID, $element->getName()); ?>"><?php echo htmlspecialchars($element->getLabel()); ?></label>
<?php endif; ?>